UX-508 Remove visual indicator for required fields
SparkPost/matchbox pull request #829
Opened 2021-04-26 18:34 UTC by jonambas

### What Changed
- Removes the visual `*` required indicator from all fields

### How To Test or Verify
- Run libby
- Visit the following stories:
  - Select
  - Textfield
  - Checkbox
  - Radio.Group 
  - ListBox
- Verify that when they are required, they apply the `required` HTML attribute but do not render anything visually

### PR Checklist

- [ ] Add the correct `type` label
- [ ] Pull request approval from #uxfe or #design-guild

2021-04-27 21:39 UTC, logansparlin requested changes
Looks good, just one comment about radio group

2021-04-27 21:39 UTC, logansparlin commented on packages/matchbox/src/components/Radio/Group.js
> +  const { children, label, labelHidden, optional, ...rest } = props;
Should probably have a `ScreenReaderOnly` with required or set aria-required="true" on the input

2021-04-28 15:49 UTC, jonambas commented
@logansparlin Ready for another pass!

2021-05-04 21:38 UTC, logansparlin approved these changes
Looks good!

2021-05-06 17:12 UTC, merged