UX-619 convert ComboBox to typescript
SparkPost/matchbox pull request #965
Opened 2021-09-13 17:13 UTC by logansparlin

### What Changed

### How To Test or Verify

### PR Checklist

- [ ] Add the correct `type` label
- [ ] Pull request approval from #uxfe or #design-guild

2021-09-13 17:37 UTC, bm-nhs approved these changes

2021-09-13 17:38 UTC, bm-nhs commented
😎lgtm

2021-09-14 12:57 UTC, jonambas requested changes
Few comments

2021-09-14 12:57 UTC, jonambas commented on packages/matchbox/src/components/ComboBox/ComboBox.tsx
> +  function getChild(name?: string, passedProps?: { children?: ReactNode }) {
Should we replace this with the other `getChild` helper?

2021-09-14 12:57 UTC, jonambas commented on packages/matchbox/src/components/ComboBox/ComboBoxTextField.tsx
> +  itemToString?: (any) => string;
did you mean `(item: any)` ?

2021-09-14 12:57 UTC, jonambas commented on packages/matchbox/src/components/ComboBox/ComboBoxTextField.tsx
>  import PropTypes from 'prop-types';
Can remove Proptypes

2021-09-14 12:57 UTC, jonambas commented on packages/matchbox/src/components/ComboBox/ComboBoxTextField.tsx
> +  itemToString?: (any) => string;
I guess you could type it to `string | { [k: string]: any }` but not sure if worth it

2021-09-14 12:57 UTC, jonambas commented on packages/matchbox/src/components/ComboBox/ComboBoxMenu.tsx
>  import PropTypes from 'prop-types';
Can remove PropTypes

2021-09-14 20:03 UTC, jonambas approved these changes
Looks good

2021-09-15 13:39 UTC, merged